### PR TITLE
Added a clearer registration success message to users.

### PR DESCRIPTION
**Pull request by s3w47m88**

### CODE REVIEW

**Comment by s3w47m88** [comment]
Was this rejected? If so, would you be willing to explain why?

**Comment by ahornero** [comment]
Ouch, sorry I didn't mean that, and then I forgot to explain you the situation. Not rejected, but I can not include these modifications in the main branch since they will modify the interaction with other languages within the plugin (i18n issue when you modify the main strings). The best idea here it could be to include them in the corresponding po/mo file for your English variant. What do you think?

**Comment by s3w47m88** [comment]
I'm happy to hear that. :) That makes perfect sense. I will put this on my to-do list. Might be a couple of weeks before I have a chance to do it though. Thank you!

**Comment by ahornero** [comment]
No problem, just let me know. Thanks to you.

**Pull request closed without merging**
